server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: email-service
  rabbitmq:
    host: localhost
    port: 5672
    username: -------
    password: -------
    queue: email_queue
    queueErros: email_queue_erro
    exchange: email_exchange
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email-service?useTimezone=true&serverTimezone=America/Sao_Paulo
    username: -------
    password: -------
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    url: jdbc:mysql://localhost:3306/
    schemas: email-service
    user: -------
    password: -------
  mail:
    configs:
      - alias: principal
        host: -------
        username: -------
        password: -------
        port: 465
        smtpAuth: true
        startTlsEnable: true
        sslEnable: true
        startTlsRequered: true
      - alias: outro
        host: -------
        username: -------
        password: -------
        port: 465
        smtpAuth: true
        startTlsEnable: true
        sslEnable: true
        startTlsRequered: true
  profiles:
    active:
    - production
  
